import { createElement, type ComponentType, type SVGProps } from 'react';
import {
  Activity,
  AlignLeft,
  Apple,
  Badge,
  BadgeCheck,
  BarChart3,
  Bed,
  BedDouble,
  Beef,
  Beer,
  Bike,
  Bone,
  BookOpen,
  BookOpenCheck,
  Brain,
  BrickWall,
  Briefcase,
  Building,
  Building2,
  CakeSlice,
  Calculator,
  CalendarCheck,
  CalendarDays,
  Camera,
  Car,
  CarFront,
  ChefHat,
  CircleEllipsis,
  ClipboardCheck,
  Clock,
  Code,
  Coffee,
  Columns2,
  Copy,
  CreditCard,
  Croissant,
  Database,
  Disc3,
  DraftingCompass,
  Droplets,
  Dumbbell,
  Euro,
  FileText,
  Files,
  Flower,
  Flower2,
  Gem,
  Glasses,
  Globe,
  GraduationCap,
  Grid3X3,
  GripVertical,
  Hammer,
  Hand,
  HandHeart,
  Handshake,
  HardHat,
  Heading,
  Heart,
  HeartHandshake,
  HelpCircle,
  History,
  Home,
  Image,
  Images,
  Key,
  KeyRound,
  Lamp,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  LayoutPanelTop,
  LifeBuoy,
  ListChecks,
  ListOrdered,
  Lock,
  Mail,
  Map,
  MapPin,
  Martini,
  Monitor,
  Medal,
  Megaphone,
  Menu,
  Music,
  Newspaper,
  Package,
  PaintRoller,
  Palette,
  PartyPopper,
  PawPrint,
  PenTool,
  PencilRuler,
  Plus,
  Pizza,
  Presentation,
  Quote,
  Receipt,
  Route,
  Ruler,
  Scale,
  School,
  Scissors,
  Search,
  Send,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Smile,
  Sparkles,
  SprayCan,
  Stethoscope,
  Tablet,
  Tent,
  TentTree,
  Text,
  Trash2,
  TrafficCone,
  Trees,
  Trophy,
  Truck,
  UserCheck,
  UserPlus,
  UserRound,
  UserRoundCheck,
  Users,
  Utensils,
  UtensilsCrossed,
  Waves,
  Wheat,
  Wine,
  Wrench,
  Zap,
  Undo2,
  Redo2,
  Eye,
  EyeOff,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ExternalLink,
  Check,
  X,
  RotateCcw,
  ChevronDown,
  Upload,
  TriangleAlert,
  CircleCheck,
  Rocket,
  PanelLeft,
  SlidersHorizontal,
  Type,
  MousePointerClick,
  Archive,
  ArchiveRestore,
  GitCompare,
  Sparkle,
  Info,
  Pencil,
} from 'lucide-react';
import { cn } from '../lib';

/**
 * Jeu d icones.
 *
 * Les icones sont importees NOMMEMENT plutot que via la table dynamique de
 * lucide : seul ce qui est reellement utilise entre dans le paquet final.
 * Importer `icons` en entier ajouterait plus d un millier de composants au
 * bundle pour n en afficher qu une centaine.
 *
 * Un nom inconnu retombe sur une icone neutre : une entree de menu sans icone
 * reste utilisable, une exception de rendu ne le serait pas.
 *
 * FICHIER PARTIELLEMENT GENERE : la table ci-dessous est derivee des noms
 * declares dans @stax/business et @stax/site-engine.
 */

export type IconName = keyof typeof ICONS;

type LucideIcon = ComponentType<SVGProps<SVGSVGElement>>;

const ICONS = {
  undo: Undo2,
  redo: Redo2,
  eye: Eye,
  'eye-off': EyeOff,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'external-link': ExternalLink,
  check: Check,
  x: X,
  'rotate-ccw': RotateCcw,
  'chevron-down': ChevronDown,
  upload: Upload,
  'alert-triangle': TriangleAlert,
  'circle-check': CircleCheck,
  rocket: Rocket,
  'panel-left': PanelLeft,
  sliders: SlidersHorizontal,
  type: Type,
  'mouse-pointer-click': MousePointerClick,
  archive: Archive,
  'archive-restore': ArchiveRestore,
  compare: GitCompare,
  sparkle: Sparkle,
  info: Info,
  pencil: Pencil,
  activity: Activity,
  'align-left': AlignLeft,
  apple: Apple,
  badge: Badge,
  'badge-check': BadgeCheck,
  'bar-chart-3': BarChart3,
  bed: Bed,
  'bed-double': BedDouble,
  beef: Beef,
  beer: Beer,
  bike: Bike,
  bone: Bone,
  'book-open': BookOpen,
  'book-open-check': BookOpenCheck,
  brain: Brain,
  'brick-wall': BrickWall,
  briefcase: Briefcase,
  building: Building,
  'building-2': Building2,
  'cake-slice': CakeSlice,
  calculator: Calculator,
  'calendar-check': CalendarCheck,
  'calendar-days': CalendarDays,
  camera: Camera,
  car: Car,
  'car-front': CarFront,
  'chef-hat': ChefHat,
  'circle-ellipsis': CircleEllipsis,
  'clipboard-check': ClipboardCheck,
  clock: Clock,
  code: Code,
  coffee: Coffee,
  'columns-2': Columns2,
  copy: Copy,
  'credit-card': CreditCard,
  croissant: Croissant,
  database: Database,
  'disc-3': Disc3,
  'drafting-compass': DraftingCompass,
  droplets: Droplets,
  dumbbell: Dumbbell,
  euro: Euro,
  'file-text': FileText,
  files: Files,
  flower: Flower,
  'flower-2': Flower2,
  gem: Gem,
  glasses: Glasses,
  globe: Globe,
  'graduation-cap': GraduationCap,
  'grid-3x3': Grid3X3,
  'grip-vertical': GripVertical,
  hammer: Hammer,
  hand: Hand,
  'hand-heart': HandHeart,
  handshake: Handshake,
  'hard-hat': HardHat,
  heading: Heading,
  heart: Heart,
  'heart-handshake': HeartHandshake,
  'help-circle': HelpCircle,
  history: History,
  home: Home,
  image: Image,
  images: Images,
  key: Key,
  'key-round': KeyRound,
  lamp: Lamp,
  landmark: Landmark,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  'layout-panel-top': LayoutPanelTop,
  'life-buoy': LifeBuoy,
  'list-checks': ListChecks,
  'list-ordered': ListOrdered,
  lock: Lock,
  mail: Mail,
  map: Map,
  'map-pin': MapPin,
  martini: Martini,
  monitor: Monitor,
  medal: Medal,
  megaphone: Megaphone,
  menu: Menu,
  music: Music,
  newspaper: Newspaper,
  package: Package,
  'paint-roller': PaintRoller,
  palette: Palette,
  'party-popper': PartyPopper,
  'paw-print': PawPrint,
  'pen-tool': PenTool,
  'pencil-ruler': PencilRuler,
  pizza: Pizza,
  plus: Plus,
  presentation: Presentation,
  quote: Quote,
  receipt: Receipt,
  route: Route,
  ruler: Ruler,
  scale: Scale,
  school: School,
  scissors: Scissors,
  search: Search,
  send: Send,
  'shield-check': ShieldCheck,
  shirt: Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  smile: Smile,
  smartphone: Smartphone,
  sparkles: Sparkles,
  'spray-can': SprayCan,
  stethoscope: Stethoscope,
  tent: Tent,
  tablet: Tablet,
  'tent-tree': TentTree,
  text: Text,
  'traffic-cone': TrafficCone,
  'trash-2': Trash2,
  trees: Trees,
  trophy: Trophy,
  truck: Truck,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'user-round': UserRound,
  'user-round-check': UserRoundCheck,
  users: Users,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  waves: Waves,
  wheat: Wheat,
  wine: Wine,
  wrench: Wrench,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>;

export interface IconProps {
  name: string;
  className?: string;
  /** Taille en pixels. Les icones sont dessinees sur une grille de 24. */
  size?: number;
  /** Rend l icone perceptible par un lecteur d ecran, avec ce libelle. */
  label?: string;
}

export function Icon({ name, className, size = 16, label }: IconProps) {
  const component = (ICONS as Record<string, LucideIcon>)[name] ?? CircleEllipsis;
  return createElement(component, {
    width: size,
    height: size,
    strokeWidth: 1.75,
    className: cn('shrink-0', className),
    'aria-hidden': label ? undefined : true,
    role: label ? 'img' : undefined,
    'aria-label': label,
    focusable: 'false',
  } as SVGProps<SVGSVGElement>);
}

export function hasIcon(name: string): name is IconName {
  return name in ICONS;
}
